/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "validator": {
        "isEmail": string;
        "length": string;
        "isString": string;
        "passwordFormat": string;
        "byteSize": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
